---
title: "Comparison of Algortihm and Selection of Algorithm"
output: html_notebook
---

Setup for all
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(magrittr)
library(tidyverse)
library(Rtsne)
library(slider)
library(factoextra)
library(stringdist)
library(cluster)
library(kernlab)
library(fpc)

```

Epitope Identification
```{r}
#Functions for epitope identification
get_epitope_sequences <- function(fn, length_threshold = 10) {
  readr::read_csv(file = fn, show_col_types = FALSE) %>%
    dplyr::select(pdb, chain, epitope, residue) %>%
    dplyr::mutate(
      epitope_sum = slider::slide_dbl(
        epitope, sum,
        .before = floor(length_threshold/2),
        .after  = floor(length_threshold/2),
        .complete = FALSE
      ),
      epitope_av = epitope_sum/length_threshold,
      epitope    = dplyr::if_else(epitope_av > 0.75, TRUE, epitope),
      epitope_index = cumsum(na.omit(c(0, (epitope * !dplyr::lag(epitope, n = 1L)))))
    ) %>%
    dplyr::filter(epitope) %>%
    dplyr::group_by(epitope_index) %>% dplyr::mutate(Length = dplyr::n()) %>% dplyr::ungroup() %>%
    dplyr::filter(Length > length_threshold) %>%
    tidyr::nest(data = residue, .by = c(pdb, chain, epitope_index)) %>%
    dplyr::group_by(epitope_index) %>%
    dplyr::mutate(sequence = paste0(unlist(data), collapse = "")) %>%
    dplyr::select(-c(data, chain)) %>%
    dplyr::ungroup() %>%
    dplyr::select(-epitope_index) %>%
    dplyr::group_by(sequence) %>%
    dplyr::mutate(count = dplyr::n_distinct(pdb)) %>%
    tidyr::nest(seq_ids = pdb) %>%
    dplyr::ungroup() %>%
    dplyr::distinct() %>%
    tibble::rowid_to_column("epitope_index")
}

compare_epitopes <- function(epitope_df) {
  epitope_df %>%
    dplyr::mutate(X = "X") %>%
    dplyr::full_join(
      epitope_df %>%
        dplyr::rename(query = sequence,
                      query_epitope_index = epitope_index) %>%
        dplyr::select(query_epitope_index, query) %>%
        dplyr::mutate(X = "X"),
      by = "X", relationship = "many-to-many"
    ) %>%
    dplyr::select(-X) %>%
    dplyr::mutate(similarity = stringdist::stringsim(sequence, query)) %>%
    dplyr::mutate(
      epitope_index       = paste0("epitope_", as.character(epitope_index)),
      query_epitope_index = paste0("epitope_", as.character(query_epitope_index))
    )
}

generate_epitope_similarity_matrix <- function(epitope_comparison_df) {
  epitope_comparison_df %>%
    dplyr::select(epitope_index, query_epitope_index, similarity) %>%
    tidyr::pivot_wider(
      id_cols = epitope_index,
      names_from = query_epitope_index,
      values_from = similarity
    ) %>%
    tibble::column_to_rownames("epitope_index") %>%
    as.matrix()
}

plot_epitope_tsne <- function(S, epitope_df, protein, proline_frac = 0.40) {
  N <- nrow(S); safe_perp <- min(50, floor((N - 1) / 3))
  ts_obj <- Rtsne::Rtsne(S, perplexity = max(5, safe_perp))

  meta <- epitope_df %>%
    dplyr::mutate(
      epitope_index_chr = paste0("epitope_", epitope_index),
      proline_fraction  = stringr::str_count(stringr::str_to_upper(sequence), "P") / nchar(sequence),
      is_proline_rich   = proline_fraction >= proline_frac
    ) %>%
    dplyr::select(epitope_index_chr, count, cluster, is_proline_rich) %>%
    dplyr::distinct()

  idx_tbl <- tibble::tibble(epitope_index_chr = rownames(S)) %>%
    dplyr::left_join(meta, by = "epitope_index_chr")

  proj_df <- dplyr::bind_cols(
    tibble::as_tibble(ts_obj$Y) %>% dplyr::rename(x = V1, y = V2),
    idx_tbl %>% dplyr::select(count, cluster, is_proline_rich)
  ) %>% dplyr::mutate(cluster = as.factor(cluster))

  show_proline <- protein %in% c("PspA","PspC")

  ggplot(proj_df, aes(x = x, y = y)) +
    geom_point(aes(size = count, fill = cluster),
               alpha = 0.7, shape = 21, stroke = 0.6, colour = "black") +
    {
      if (show_proline) {
        geom_point(
          data = subset(proj_df, is_proline_rich %in% TRUE),
          shape = 21, stroke = 0.9, fill = NA, colour = "red", alpha = 0.95
        )
      }
    } +
    guides(size = guide_legend(title = "Count",
                               override.aes = list(fill = "grey70", colour = NA, alpha = 1, shape = 21)),
           fill = guide_legend(title = "Cluster")) +
    labs(
      title = paste0(protein, " t-SNE (Length threshold = ", length_threshold, ")"),
      subtitle = paste0("Perplexity = ", max(5, safe_perp)),
      x = NULL, y = NULL
    ) +
    theme_bw()
}

```
Prep for the wanted length and proline fraction. Uses the same values and same protein
```{r}

length_threshold <- 10
proline_frac     <- 0.40
prot             <- "PspA"
in_file          <- "/Users/omeryurttutmus/Desktop/taxa/Filtered_Discotope_LPXTG/pspA_filtered_epitopes_justInterpro.csv"
out_dir          <- "epitope_outputs_compare"
dir.create(out_dir, showWarnings = FALSE)

epitope_df <- get_epitope_sequences(in_file, length_threshold = length_threshold)

epitope_comparison_df <- compare_epitopes(epitope_df)
S <- generate_epitope_similarity_matrix(epitope_comparison_df)
S[is.na(S)] <- 0
D <- 1 - S; diag(D) <- 0
dist_obj <- as.dist(D)

```
Clustering with the same K for different algorithms
```{r}
K <- 4

# K-means
set.seed(1)
km <- eclust(S, "kmeans", k = K, nboot = 10)
labs_km <- km$cluster[rownames(S)]
labs_km <- as.integer(labs_km)        
names(labs_km) <- rownames(S)

# Spectral
sp <- specc(as.matrix(S), centers = K)
labs_sp <- as.integer(sp@.Data)
names(labs_sp) <- rownames(S) 

# Hierarchical (Ward.D2)
hc <- hclust(dist_obj, method = "ward.D2")
labs_hc <- cutree(hc, k = K)
names(labs_hc) <- rownames(S)


```
Comparison of the algorithms using the parameters both visually and quantitatively
```{r}
attach_and_save <- function(labels, method_tag) {
  cls_tbl <- tibble::tibble(
    epitope_index = as.integer(gsub("^epitope_", "", names(labels))),
    cluster = as.character(as.integer(labels))
  )
  df <- epitope_df %>% dplyr::left_join(cls_tbl, by = "epitope_index")

#Plot
  p <- plot_epitope_tsne(S, df, protein = prot, proline_frac = proline_frac)
  ggsave(file.path(out_dir, paste0(prot, "_tsne_", method_tag, "_k", K, ".png")),
         plot = p, width = 8, height = 6, dpi = 300)

#Get CSV file for quantitative comparison
  df %>%
    dplyr::select(epitope_index, sequence, count, cluster, seq_ids) %>%
    dplyr::mutate(
      seq_ids = vapply(seq_ids, function(tb) paste(unique(tb$pdb), collapse = ";"),
                       FUN.VALUE = character(1))
    ) %>%
    readr::write_csv(file.path(out_dir, paste0(prot, "_epitopes_", method_tag, "_k", K, ".csv")))

  labs_ordered <- df %>%
    mutate(rn = paste0("epitope_", epitope_index)) %>%
    filter(rn %in% rownames(S)) %>%
    arrange(match(rn, rownames(S))) %>%
    pull(cluster) %>% as.integer(as.factor(.))

  cs <- fpc::cluster.stats(d = dist_obj, clustering = labs_ordered)
  tibble::tibble(
    method = method_tag,
    k = K,
    avg_silhouette = cs$avg.silwidth,
    ch_index = cs$ch,
    dunn_index = cs$dunn
  )
}

scores <- bind_rows(
  attach_and_save(labs_km, "kmeans"),
  attach_and_save(labs_sp, "spectral"),
  attach_and_save(labs_hc, "hclust_wardD2")
)

print(scores %>% arrange(desc(avg_silhouette)))
scores %>% 
  arrange(desc(avg_silhouette)) %>% 
  write.csv("scores_sorted.csv", row.names = FALSE)
```